export const english = {
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.retry': 'Retry',
  'home.tasks': 'Tasks',
  'home.noTaskSources': 'No task sources connected',
  'home.openProviderTasks': 'Open {provider} tasks',
  'home.removeFailedTitle': 'Could not remove host',
  'home.tryAgain': 'Please try again.',
  'home.connectDesktop': 'Connect your desktop',
  'home.connectDesktopBody':
    'Pair with Orca on your computer to check on your agents, jump into any terminal, and drive work from your phone.',
  'home.pairDesktop': 'Pair Desktop',
  'home.howItWorks': 'How it works',
  'home.welcomeBack': 'Welcome back',
  'home.agentsSpawned': 'Agents spawned',
  'home.agentTime': 'Agent time',
  'home.prsCreated': 'PRs created',
  'home.desktops': 'Desktops',
  'home.resume': 'Resume',
  'home.quickActions': 'Quick Actions',
  'home.newWorkspace': 'New Workspace',
  'home.createWorkspaceOn': 'Create Workspace On',
  'home.accountUsage': 'Account usage',
  'home.systemDefault': 'System default',
  'home.connect': 'Connect',
  'home.reconnect': 'Reconnect',
  'home.disconnect': 'Disconnect',
  'home.editHost': 'Edit host',
  'home.remove': 'Remove',
  'home.removeHost': 'Remove Host',
  'home.removeHostMessage': 'Remove "{name}"? You can re-pair later.',
  'home.stepOpenTitle': 'Open Orca desktop',
  'home.stepOpenBody': 'Go to Settings → Mobile and generate a pairing QR code.',
  'home.stepPairTitle': 'Scan or paste the code',
  'home.stepPairBody': 'Open pairing, then scan the QR code or choose manual setup.',
  'home.stepConnectedTitle': "You're connected",
  'home.stepConnectedBody': 'Your desktop will appear here. Everything is encrypted end-to-end.',
  'home.durationDaysHours': '{days}d {hours}h',
  'home.durationHoursMinutes': '{hours}h {minutes}m',
  'home.durationMinutes': '{minutes}m',
  'host.connected': 'Connected',
  'host.connecting': 'Connecting…',
  'host.disconnected': 'Disconnected',
  'host.reconnecting': 'Reconnecting…',
  'host.cantConnect': "Can't connect",
  'host.cantReachDesktop': "Can't reach desktop",
  'host.pairingInvalid': 'Pairing invalid — re-pair with your desktop',
  'host.pairingInvalidStatus': 'Pairing invalid',
  'host.pairingTemporarilyUnavailable': 'Pairing temporarily unavailable',
  'host.repairHint': 'Tap to re-pair with your desktop',
  'host.unlockRetryHint': 'Unlock your phone, then tap to retry',
  'host.checkTailscale': 'check Tailscale',
  'host.statusWithHint': '{status} — {hint}',
  'host.pathRelay': 'Orca Relay',
  'host.pathTailscale': 'Direct · Tailscale',
  'host.pathLan': 'Direct · LAN',
  'host.worktreeOne': '{count} worktree',
  'host.worktreeMany': '{count} worktrees',
  'host.activeWorktrees': ' · {count} active',
  'host.worktreeListUnavailable': 'Worktree list unavailable',
  'host.lastKnownWorktrees': 'Last known: {summary}',
  'host.discoveryHint': 'Update desktop Orca and sign in to connect from anywhere',
  'host.openAccessibility': 'Open {name}',
  'host.actionsAccessibility': 'Actions for {name}',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.terminal': 'Terminal',
  'settings.chatUi': 'Chat UI',
  'settings.browser': 'Browser',
  'settings.voice': 'Voice',
  'settings.notifications': 'Notifications',
  'settings.troubleshooting': 'Troubleshooting',
  'settings.about': 'About',
  'settings.credentialCleanup': 'Pairing credential cleanup',
  'settings.cleanupRetryFailed': "Cleanup still couldn't be confirmed. Try again later.",
  'settings.cleanupPendingOne':
    "Couldn't confirm cleanup for {count} pairing credential on this device.",
  'settings.cleanupPendingMany':
    "Couldn't confirm cleanup for {count} pairing credentials on this device.",
  'settings.cleanupUnreadable': "Couldn't check cleanup status on this device. Retry to be safe.",
  'settings.retryCleanupA11y': 'Retry clearing pairing credentials',
  'settings.privacy': 'Privacy Policy',
  'settings.support': 'Support',
  'language.title': 'Language',
  'language.description': 'Choose the language used on Home, Settings, and Pairing screens.',
  'language.english': 'English',
  'language.simplifiedChinese': '简体中文',
  'language.saveFailedTitle': 'Could not change language',
  'language.saveFailedBody': 'Please try again.',
  'chat.scrollToLatest': 'Scroll to latest',
  'chat.collapseTools': 'Collapse',
  'chat.tools': 'Tools',
  'chat.stopAgent': 'Stop the agent',
  'chat.stop': 'Stop',
  'chat.messageNotSentReconnecting': 'Message not sent — reconnecting…',
  'chat.messageNotSent': 'Message not sent',
  'chat.reconnecting': 'Reconnecting…',
  'chat.waitingForTerminal': 'Waiting for terminal…',
  'chat.composerPlaceholder': 'Message, @files, /commands',
  'pair.title': 'Pair with desktop',
  'pair.cameraDisabled': 'Camera Access Disabled',
  'pair.scanOrManual':
    'Scan the QR code from Orca on your desktop, or enter the pairing details manually.',
  'pair.enableCameraOrManual':
    'Enable camera access in Settings, or enter the pairing details manually.',
  'pair.continue': 'Continue',
  'pair.openSettings': 'Open Settings',
  'pair.manualSetup': 'Manual setup',
  'pair.stepOpen': 'Open Orca on your computer',
  'pair.stepSettings': 'Go to Settings → Mobile',
  'pair.stepScan': 'Scan the QR code or use manual setup',
  'pair.invalidQr': 'Not a valid Orca QR code',
  'pair.invalidCode': 'Not a valid pairing code — copy it from your computer and paste again',
  'pair.pasteTitle': 'Paste pairing code',
  'pair.pasteMessage': 'Copy the code shown under the QR on your computer.',
  'pair.pastePlaceholder': 'orca://pair?code=... or paste the code',
  'pair.connecting': 'Connecting…',
  'pair.log': 'Pairing log',
  'pair.tryAgain': 'Try Again',
  'pair.timeout': "Couldn't connect within {seconds}s — see log below for where it stalled",
  'pair.failed': 'Pairing failed: {message}'
} as const

export type TranslationKey = keyof typeof english
export type TranslationCatalog = Record<TranslationKey, string>
