import type { TranslationCatalog } from './en'

export const simplifiedChinese = {
  'common.back': '返回',
  'common.cancel': '取消',
  'common.retry': '重试',
  'home.tasks': '任务',
  'home.noTaskSources': '尚未连接任务来源',
  'home.openProviderTasks': '打开 {provider} 任务',
  'home.removeFailedTitle': '无法移除主机',
  'home.tryAgain': '请重试。',
  'home.connectDesktop': '连接桌面端',
  'home.connectDesktopBody':
    '与电脑上的 Orca 配对，即可查看 Agent、进入任意终端并通过手机推进工作。',
  'home.pairDesktop': '配对桌面端',
  'home.howItWorks': '使用方式',
  'home.welcomeBack': '欢迎回来',
  'home.agentsSpawned': '已启动 Agent',
  'home.agentTime': 'Agent 用时',
  'home.prsCreated': '已创建 PR',
  'home.desktops': '桌面端',
  'home.resume': '继续',
  'home.quickActions': '快捷操作',
  'home.newWorkspace': '新建工作区',
  'home.accountUsage': '账户用量',
  'home.systemDefault': '系统默认',
  'home.connect': '连接',
  'home.reconnect': '重新连接',
  'home.disconnect': '断开连接',
  'home.editHost': '编辑主机',
  'home.remove': '移除',
  'home.removeHost': '移除主机',
  'home.removeHostMessage': '移除“{name}”？之后仍可重新配对。',
  'home.stepOpenTitle': '打开 Orca 桌面端',
  'home.stepOpenBody': '前往“设置 → 移动端”，生成配对二维码。',
  'home.stepPairTitle': '扫描或粘贴配对码',
  'home.stepPairBody': '打开配对页面，扫描二维码或选择手动配置。',
  'home.stepConnectedTitle': '连接完成',
  'home.stepConnectedBody': '桌面端会显示在这里，所有内容均采用端到端加密。',
  'home.durationDaysHours': '{days}天 {hours}小时',
  'home.durationHoursMinutes': '{hours}小时 {minutes}分钟',
  'home.durationMinutes': '{minutes}分钟',
  'host.connected': '已连接',
  'host.connecting': '正在连接…',
  'host.disconnected': '已断开连接',
  'host.reconnecting': '正在重新连接…',
  'host.cantConnect': '无法连接',
  'host.cantReachDesktop': '无法连接桌面端',
  'host.pairingInvalid': '配对已失效，请重新与桌面端配对',
  'host.checkTailscale': '请检查 Tailscale',
  'host.statusWithHint': '{status} — {hint}',
  'host.pathRelay': 'Orca 中继',
  'host.pathTailscale': '直连 · Tailscale',
  'host.pathLan': '直连 · 局域网',
  'host.worktreeOne': '{count} 个工作区',
  'host.worktreeMany': '{count} 个工作区',
  'host.activeWorktrees': ' · {count} 个活跃工作区',
  'host.worktreeListUnavailable': '工作区列表不可用',
  'host.discoveryHint': '更新桌面端 Orca 并登录，即可随时随地连接',
  'settings.title': '设置',
  'settings.language': '语言',
  'settings.terminal': '终端',
  'settings.chatUi': '聊天界面',
  'settings.browser': '浏览器',
  'settings.voice': '语音',
  'settings.notifications': '通知',
  'settings.troubleshooting': '故障排查',
  'settings.about': '关于',
  'settings.credentialCleanup': '清理配对凭据',
  'settings.cleanupRetryFailed': '仍无法确认清理结果，请稍后重试。',
  'settings.cleanupPendingOne': '无法确认本设备上 {count} 个配对凭据是否已清理。',
  'settings.cleanupPendingMany': '无法确认本设备上 {count} 个配对凭据是否已清理。',
  'settings.cleanupUnreadable': '无法检查本设备的清理状态，请重试以确保安全。',
  'settings.retryCleanupA11y': '重试清理配对凭据',
  'settings.privacy': '隐私政策',
  'settings.support': '支持',
  'language.title': '语言',
  'language.description': '选择首页、设置和配对页面使用的语言。',
  'language.english': 'English',
  'language.simplifiedChinese': '简体中文',
  'language.saveFailedTitle': '无法更改语言',
  'language.saveFailedBody': '请重试。',
  'chat.scrollToLatest': '滚动到最新消息',
  'chat.collapseTools': '收起',
  'chat.tools': '工具',
  'chat.stopAgent': '停止 Agent',
  'chat.stop': '停止',
  'chat.messageNotSentReconnecting': '消息未发送，正在重新连接…',
  'chat.messageNotSent': '消息未发送',
  'chat.reconnecting': '正在重新连接…',
  'chat.waitingForTerminal': '正在等待终端…',
  'chat.composerPlaceholder': '输入消息、@文件或/命令',
  'pair.title': '与桌面端配对',
  'pair.cameraDisabled': '相机权限已关闭',
  'pair.scanOrManual': '扫描桌面端 Orca 中的二维码，或手动输入配对信息。',
  'pair.enableCameraOrManual': '请在系统设置中启用相机权限，或手动输入配对信息。',
  'pair.continue': '继续',
  'pair.openSettings': '打开设置',
  'pair.manualSetup': '手动配置',
  'pair.stepOpen': '在电脑上打开 Orca',
  'pair.stepSettings': '前往“设置 → 移动端”',
  'pair.stepScan': '扫描二维码或使用手动配置',
  'pair.invalidQr': '不是有效的 Orca 二维码',
  'pair.invalidCode': '不是有效的配对码，请从电脑端复制后重新粘贴',
  'pair.pasteTitle': '粘贴配对码',
  'pair.pasteMessage': '复制电脑端二维码下方显示的配对码。',
  'pair.pastePlaceholder': 'orca://pair?code=... 或粘贴配对码',
  'pair.connecting': '正在连接…',
  'pair.log': '配对日志',
  'pair.tryAgain': '重试',
  'pair.timeout': '无法在 {seconds} 秒内连接，请查看下方日志确认停滞位置',
  'pair.failed': '配对失败：{message}'
} satisfies TranslationCatalog
